---
- hosts: localhost
  connection: local
  tasks:
    - name: Ensure Python 3 & Git are installed
      package:
        name:
          - python3
          - python3-pip
          - git
        state: present

    - name: Ensure Python typing-extensions package is not installed
      package:
        name: python3-typing-extensions
        state: absent

    - name: Set extra_args var
      set_fact:
        extra_args: ""

    - name: Set extra_args var in py3.11
      set_fact:
        extra_args: --break-system-packages
      when: ansible_python_version is version('3.11', '>=')

    - name: Clone EOSC Data Transfer Client repository
      git:
        repo: 'https://gitlab.cern.ch/batistal/eosc-data-transfer-client.git'
        dest: '/tmp/eosc-data-transfer-client'
        version: 'main'

    - name: Install requirements
      pip:
        requirements: /tmp/eosc-data-transfer-client/requirements.txt
        extra_args: "{{ extra_args }}"

    - name: Install EOSC Data Transfer Client
      pip:
        name: "/tmp/eosc-data-transfer-client"
        extra_args: "{{ extra_args }}"
