---
- hosts: localhost
  connection: local
  tasks:
    - name: Ensure Python 3 & Git are installed
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Set extra_args var
      set_fact:
        extra_args: ""

    - name: Set extra_args var in py3.11
      set_fact:
        extra_args: --break-system-packages
      when: ansible_python_version is version('3.11', '>=')

    - name: Install PyHandle
      ansible.builtin.pip:
        name: "pyhandle"
        extra_args: "{{ extra_args }}"
