tosca_definitions_version: tosca_simple_yaml_1_0

imports:
  - template_file: https://raw.githubusercontent.com/grycap/tosca/refs/heads/eosc_beyond/templates/kubernetes.yaml
 
topology_template:

  inputs:

    fe_cpus: 2
    fe_mem: 4 GB
 
    wn_num: 1
    wn_cpus: 2
    wn_mem: 4 GB

    galaxy_admin_users:
      type: string
      description: Administrative users - set this to a comma-separated list of valid Galaxy users (email addresses).
      default: 'admin@admin.com'

  node_templates:

    galaxy:
      type: tosca.nodes.SoftwareComponent
      requirements:
        - host: front
        - dependency: lrms_front_end
      interfaces:
        Standard:
          configure:
            implementation: https://raw.githubusercontent.com/grycap/tosca/main/artifacts/k8s_galaxy.yml
            inputs:
              galaxy_admin_users: { get_input: galaxy_admin_users }
              galaxy_brand: 'IM Deployed Galaxy K8s Cluster'
              galaxy_max_mem: { get_input: wn_mem }
              galaxy_max_cores: { get_input: wn_cpus }

  outputs:
    galaxy_endpoint:
      value: { concat: [ 'https://', get_attribute: [ front, public_address, 0 ], '/galaxy/' ] }
