---
- hosts: localhost
  connection: local
  tasks:

    - when: k8s_spec != ''
      block:

      - name: Create temporary file
        tempfile:
          state: file
          suffix: k8s
        register: tempfile
  
      - name: Create the K8s file spec
        copy:
          content: "{{ k8s_spec }}"
          dest: "{{ tempfile.path }}"
          mode: '644'
        when: not k8s_spec.startswith('http')
  
      - name: Download the K8s file spec
        get_url:
          url: "{{ k8s_spec }}"
          dest: "{{ tempfile.path }}"
          mode: '644'
        when: "k8s_spec.startswith('http')"
  
      - name: Apply the K8s spec
        command: kubectl apply -f {{ tempfile.path }}
        environment:
          KUBECONFIG: /etc/kubernetes/admin.conf
