---
- hosts: localhost
  connection: local
  vars:
    vnode_prefix: vnode-
    csi_driver: "{{ kube_csi_driver | default('NFS') }}"
  pre_tasks:
    # Avoid error in ntp installation in Debian
    - name: Remove systemd-timesyncd in Debian systems
      package:
        name: systemd-timesyncd
        state: absent
      ignore_errors: true
      when: ansible_family == "Debian"
  roles:
    - role: grycap.nfs
      nfs_mode: 'wn'
      when: csi_driver == 'NFS'
    - role: 'grycap.kubernetes'
      kube_type_of_node: 'wn'
      kube_server: '{{ kube_front_end_ip }}'
      kube_api_server: '{{ kube_front_end_ip }}'
