---
- hosts: localhost
  connection: local
  vars:
    server_list: "{{ nomad_server_list | default([ansible_default_ipv4.address]) }}"
    client_private_ip: "{{ IM_NODE_PRIVATE_IP | default(ansible_default_ipv4.address) }}"
    nvidia_support: "{{ nomad_nvidia_support | default(false) }}"
    launch_traefik: "{{ nomad_launch_traefik | default(false) }}"
    certs_url: "{{ consul_cert_url | default('') }}"
    consul_join: "{{ consul_server_join | default('') }}"
    from_scratch_cluster_installation: true
  pre_tasks:
    - name: Convert server_list to list
      set_fact:
        server_list:
          - "{{ server_list }}"
      when:
        - server_list is string
    - name: Set primary_datacenter
      set_fact:
        consul_primary_datacenter: "{{ nomad_input_dc | default('ifca-ai4eosc') }}"
    - name: Set primary_datacenter
      set_fact:
        consul_primary_datacenter: "{{ consul_join_datacenter | default('ifca-ai4eosc') }}"
        from_scratch_cluster_installation: false
      when: consul_join != ''
  roles:
    - role: 'grycap.docker'
      docker_nvidia_support: "{{ nvidia_support }}"

  tasks:

    - name: Set all_wn
      set_fact:
        all_wn: "{{ groups['wn'] }}"

    - name: Add pub nodes to all_wn
      set_fact:
        all_wn: "{{ all_wn + groups['wn_pub'] }}"
      when: groups['wn_pub'] is defined

    - name: Add gpu nodes to all_wn
      set_fact:
        all_wn: "{{ all_wn + groups['wn_gpu'] }}"
      when: groups['wn_gpu'] is defined


    - when: consul_join == ''
      block:

        - name: Set consul_master
          add_host:
            name: "{{ groups['front'][0] }}"
            groups:
              - consul_master
              - nomad_master

        - name: Add servers to other server nodes
          add_host:
            name: '{{ item }}'
            groups:
              - nomad_servers
              - consul_servers
              - consul
              - nomad
          with_items: "{{ groups['front'] }}"

        - name: Enable Traefik
          add_host:
            name: "{{ groups['wn_pub'][0] }}"
            groups:
              - traefik_master
          when: launch_traefik and 'wn_pub' in groups and groups['wn_pub'] | length > 0

        - name: Add client groups
          add_host:
            name: '{{ item }}'
            groups:
              - nomad_cpu_clients
              - nomad_clients
              - consul_clients
              - consul
              - nomad
          with_items: "{{ all_wn }}"

        - name: Add gpu clients
          add_host:
            name: 'none'
            groups:
              - nomad_gpu_clients

    - when: consul_join != ''
      block:

        - name: Add new servers to other server nodes
          add_host:
            name: '{{ item }}'
            groups:
              - nomad_new_servers
              - consul_new_servers
              - consul_new
              - nomad_new
              - consul_new_master
          with_items: "{{ groups['front'] }}"

        - name: Enable new Traefik
          add_host:
            name: "{{ groups['wn_pub'][0] }}"
            groups:
              - traefik_new_master
          when: launch_traefik and 'wn_pub' in groups and groups['wn_pub'] | length > 0

        - name: Add new client groups
          add_host:
            name: '{{ item }}'
            groups:
              - nomad_new_cpu_clients
              - nomad_new_clients
              - consul_new_clients
              - consul_new
              - nomad_new
          with_items: "{{ all_wn }}"

        - name: Add new gpu clients
          add_host:
            name: 'none'
            groups:
              - nomad_new_gpu_clients

    - name: Copy AI4 Ansible vars file
      copy:
        src: /opt/ai4-ansible/group_vars/all.yml
        dest: /var/tmp/ai4-ansible-vars.yml
        mode: '755'
        remote_src: true

    - name: Include roles vars
      include_vars:
        file: /var/tmp/ai4-ansible-vars.yml

    - name: Set facts
      set_fact:
        consul_public_ip: "{{ server_list[0] }}"
        consul_servers_ip: "{{ [consul_join] }}"
        my_ip: "{{ client_private_ip }}"
        username: cloudadm
        path: /opt/cloudadm/
        nomad_dc: "{{ nomad_input_dc | default('ifca-ai4eosc') }}"
        consul_dc_name: "{{ nomad_input_dc | default('ifca-ai4eosc') }}"
        primary_datacenter: "{{ consul_primary_datacenter }}"
        domain: "{{ nomad_input_domain | default('ifca') }}"
        nomad_version: "{{ nomad_input_version | default('1.7.3') }}"
        consul_version: "{{ consul_input_version | default('1.17.1') }}"
        roles_dir: /opt/ai4-ansible/
        new_certs: "{{ nomad_input_dc | default('ifca-ai4eosc') }}-certs"
        traefik_letsencrypt_email: "{{ nomad_traefik_letsencrypt_email | default('admin@test.com') }}"

    - name: Download consul + nomad certs
      get_url:
        url: "{{ certs_url }}"
        dest: "{{ path }}{{ new_certs }}.zip"
        owner: cloudadm
        mode: '0755'
      when: certs_url != ''

    - name: Invoke consul role
      include_role:
        name: consul

    - name: Invoke nomad role
      include_role:
        name: nomad
