---
- hosts: localhost
  connection: local
  handlers:
    - name: Restart Pulsar
      ansible.builtin.service:
        name: pulsar.service
        state: restarted
        enabled: yes

  tasks:
    - name: Check whether Pulsar is installed
      ansible.builtin.stat:
        path: /opt/pulsar/config/app.yml
      register: st

    - name: Fail if the file does not exist
      ansible.builtin.fail:
        msg: "It is a prerequisite to use the VGCN virtual machine image: https://github.com/usegalaxy-eu/vgcn"
      when: not st.stat.exists

    - name: Configure message queue in Pulsar
      ansible.builtin.lineinfile:
        path: /opt/pulsar/config/app.yml
        regexp: '^message_queue_url:'
        line: 'message_queue_url: pyamqp://{{ pulsar_user }}:{{ pulsar_password }}@mq.galaxyproject.eu:5671//pulsar/{{ pulsar_user }}?ssl=1'
        owner: root
        group: root
        mode: '0644'
      notify: Restart Pulsar
