---
- hosts: localhost
  connection: local
  pre_tasks:
    - name: stop firewalld
      service: name=firewalld state=stopped
      ignore_errors: true
    # Avoid error in ntp installation in Debian
    - name: Remove systemd-timesyncd in Debian systems
      package:
        name: systemd-timesyncd
        state: absent
      ignore_errors: true
      when: ansible_os_family == "Debian"
    - name: Set slurm_wn_nodenames if not defined
      set_fact:
        slurm_wn_nodenames: '{{ groups["wn"]|map("extract", hostvars, "ansible_hostname")|list if "wn" in groups else [] }}'
      when: slurm_wn_nodenames is not defined
    - name: Set slurm_vnode_prefix if not defined
      set_fact:
        slurm_vnode_prefix: 'vnode-'
      when: slurm_vnode_prefix is not defined
  roles:
    - role: grycap.nfs
      nfs_mode: 'front'
      nfs_exports: [{path: "/home", export: "{{ vnode_prefix }}*.localdomain(rw,async,no_root_squash,no_subtree_check,insecure,crossmnt)"}]
      when: slurm_nfs is undefined or slurm_nfs
    - role: grycap.slurm
      slurm_type_of_node: 'front'
      slurm_wn_num: '{{ wn_num }}'
      slurm_wn_ips: '{{ wn_ips }}'
      slurm_server_ip: '{{ slurm_front_end_ip }}'
