---
- hosts: localhost
  connection: local
  vars:
    vnode_prefix: vnode-
  pre_tasks:
    - name: Stop and disable firewalls
      service:
        name: "{{ item }}"
        enabled: false
        state: stopped
      ignore_errors: true
      loop:
        - ufw
        - firewalld
    # Avoid error in ntp installation in Debian
    - name: Remove systemd-timesyncd in Debian systems
      package:
        name: systemd-timesyncd
        state: absent
      ignore_errors: true
      when: ansible_os_family == "Debian"
    - name: Set slurm_front_end_ip if not set
      set_fact:
        slurm_front_end_ip: '{{ slurm_public_front_end_ip }}'
      when:
        - slurm_front_end_ip is not defined or slurm_front_end_ip == ''
        - slurm_public_front_end_ip is defined and slurm_public_front_end_ip != ''
  roles:
    - role: grycap.nfs
      nfs_mode: 'wn'
      nfs_client_imports: [{ local: "/home", remote: "/home", server_host: "{{ slurm_front_end_ip }}" }]
      when: slurm_nfs is undefined or slurm_nfs
    - role: grycap.slurm
      slurm_type_of_node: 'wn'
      slurm_server_ip: '{{ slurm_front_end_ip }}'
