tosca_definitions_version: tosca_simple_yaml_1_0

imports:
  - grycap_custom_types: https://raw.githubusercontent.com/grycap/tosca/main/custom_types.yaml

description: Deploy a Galaxy Server using a local LRMS.

metadata:
  template_name: VM
  template_version: "1.2.1"
  template_author: Miguel Caballer

topology_template:

  inputs:
    num_cpus:
      type: integer
      description: Number of virtual cpus for the VM
      default: 2
    mem_size:
      type: scalar-unit.size
      description: Amount of memory for the VM
      default: 4 GB
    disk_size:
      type: scalar-unit.size
      description: Size of the root disk of the VM
      default: 20 GB
    num_gpus:
      type: integer
      description: Number of GPUs to assing to this VM
      default: 0


    admin_email:
      type: string
      description: Email of the Galaxy admin user
      default: admin@admin.com
    admin_password:
      type: string
      description: Password of the Galaxy admin user
      default: adminpass
    brand:
      type: string
      description: Brand of the Galaxy portal
      default: Galaxy
    version:
      type: string
      description: Version of the Galaxy portal
      default: '24.2'
      constraints:
        - valid_values: [ '24.2', '24.1' ]


  node_templates:

    galaxy_portal:
      type: tosca.nodes.indigo.GalaxyPortal
      capabilities:
        endpoint:
          properties:
            ports:
              https:
                protocol: tcp
                source: 443
              http:
                protocol: tcp
                source: 80
      properties:
        admin_email: { get_input: admin_email }
        admin_password: { get_input: admin_password }
        brand: { get_input: brand }
        version: { get_input: version }
      requirements:
        - lrms: local_lrms
        - host: simple_node

    # type to describe a Galaxy not using any LRMS but using the local system
    local_lrms:
      type: tosca.nodes.indigo.LRMS.FrontEnd.Local
      requirements:
        - host: simple_node

    simple_node:
      type: tosca.nodes.indigo.Compute
      capabilities:
        endpoint:
          properties:
            network_name: PUBLIC
        host:
          properties:
            disk_size: { get_input: disk_size }
            num_cpus: { get_input: num_cpus }
            mem_size: { get_input: mem_size }
            num_gpus: { get_input: num_gpus }
        os:
          properties:
            type: linux
            distribution: ubuntu
            version: '22.04.4'

  outputs:
    url:
      value: { concat: [ 'https://galaxy.', get_attribute: [ simple_node, public_address, 0 ], '.nip.io/' ] }
