tosca_definitions_version: tosca_simple_yaml_1_0

imports:
  - grycap_custom_types: https://raw.githubusercontent.com/grycap/tosca/main/custom_types.yaml

description: Deploy a Galaxy Server using a local LRMS.

metadata:
  template_version: "1.2.2"
  template_name: Galaxy
  display_name: Deploy a Galaxy portal
  icon: images/galaxy.png
  tabs:
    Galaxy Data: .*
  parents:
    - simple-node-disk.yml

topology_template:

  inputs:

    admin_email:
      type: string
      description: Email of the Galaxy admin user
      default: admin@admin.com
    admin_password:
      type: string
      description: Password of the Galaxy admin user
      default: adminpass
    brand:
      type: string
      description: Brand of the Galaxy portal
      default: Galaxy
    version:
      type: string
      description: Version of the Galaxy portal
      default: '25.1'
      constraints:
        - valid_values: [ '25.1', '24.2', '24.1' ]

    dns_name:
      type: string
      description: DNS name of the Galaxy portal (leave empty to use galaxy.<node_ip>.nip.io)
      default: ''

  node_templates:

    galaxy_portal:
      type: tosca.nodes.indigo.GalaxyPortal
      capabilities:
        endpoint:
          properties:
            ports:
              https:
                protocol: tcp
                source: 443
              http:
                protocol: tcp
                source: 80
      properties:
        admin_email: { get_input: admin_email }
        admin_password: { get_input: admin_password }
        dns_name: { get_input: dns_name }
        brand: { get_input: brand }
        version: { get_input: version }
      requirements:
        - lrms: local_lrms
        - host: simple_node

    # type to describe a Galaxy not using any LRMS but using the local system
    local_lrms:
      type: tosca.nodes.indigo.LRMS.FrontEnd.Local
      requirements:
        - host: simple_node

  outputs:
    galaxy_nip_url:
      value: { concat: [ 'https://galaxy.', get_attribute: [ simple_node, public_address, 0 ], '.nip.io/' ] }
    galaxy_dns_url:
      value: { concat: [ 'https://', { get_input: dns_name }, '/' ] }
