tosca_definitions_version: tosca_simple_yaml_1_0

imports:
  - grycap_custom_types: https://raw.githubusercontent.com/grycap/tosca/main/custom_types.yaml


description: Deploy Haddock web UI.

metadata:
  template_version: "1.0.0"
  template_name: Haddock
  display_name: Deploy Haddock Web UI
  icon: images/haddock.png
  tag: devel
  web: https://www.bonvinlab.org/haddock3/
  tabs:
    Haddock Data: .*
  parents:
    - simple-node-disk.yml

topology_template:
  inputs:

    haddock_cores:
      default: 4
      description: Number of cores used by a single haddock3 job.
      type: integer

    haddock_max_jobs:
      default: 1
      description: Maximum number of concurrent haddock3 jobs.
      type: integer

    letsencrypt_email:
      default: changeme@email.com
      description: Email to be used for Let's Encrypt certificates
      type: string

    # Restrict some simple-node-disk input values

    dns_name:
      default: haddock-test.vm.fedcloud.eu
      description: DNS hostname to access the Haddock Web UI
      type: string

  node_templates:

    haddock:
      type: tosca.nodes.ec3.Application
      artifacts:
        docker_role:
          file: grycap.docker
          type: tosca.artifacts.AnsibleGalaxy.role
      capabilities:
        endpoint:
          properties:
            ports:
              port_http:
                protocol: tcp
                source: 80
              port_https:
                protocol: tcp
                source: 443
      interfaces:
        Standard:
          configure:
            implementation: https://raw.githubusercontent.com/grycap/tosca/main/artifacts/haddock_compose.yml
            inputs:
              letsencrypt_email: { get_input: letsencrypt_email }
              haddock_dns_name: { get_input: dns_name }
              haddock_public_ip: { get_attribute: [ simple_node, public_address, 0 ] }
              haddock_cores: { get_input: haddock_cores }
              haddock_max_jobs: { get_input: haddock_max_jobs }
      requirements:
        - host: simple_node

  outputs:
    haddock_url:
      value: { concat: [ 'https://', get_attribute: [ simple_node, public_address, 0 ], '/' ] }
    haddock_url_dns:
      value: { concat: [ 'https://', get_input: [ dns_name ], '/' ] }
