tosca_definitions_version: tosca_simple_yaml_1_0

imports:
  - grycap_custom_types: https://raw.githubusercontent.com/grycap/tosca/main/custom_types.yaml

description: Deploy MinIO server.

metadata:
  template_version: "1.0.0"
  template_name: MinIO
  display_name: Deploy MinIO server
  icon: images/minio.png
  tabs:
    MinIO Data:
      - minio_release
      - minio_accesskey
      - minio_secretkey
      - minio_dns_console
      - nsupdate_secret_console
      - minio_dns_api
      - nsupdate_secret_api
      - minio_letsencrypt_email
  parents:
    - simple-node-disk.yml

topology_template:
  inputs:

    minio_release:
      default: RELEASE.2023-07-21T21-12-44Z
      description: Check out https://github.com/minio/minio/tags
      type: string
    minio_accesskey:
      default: changeme
      description: Access key credential for object storage and web access
      type: string
    minio_secretkey:
      constraints:
        - min_length: 8
      default: changeme123
      description: Secret key credential for object storage and web access
      type: string
    minio_dns_console:
      default: minio.test.fedcloud.changeme
      description: DNS hostname to access MinIO console
      type: string
    nsupdate_secret_console:
      default: changeme
      description: Secret generated when registering minio.test.fedcloud.changeme via https://nsupdate.fedcloud.eu/
      type: string
    minio_dns_api:
      default: minio-api.test.fedcloud.changeme
      description: DNS hostname to access MinIO API endpoint
      type: string
    nsupdate_secret_api:
      default: changeme
      description: Secret generated when registering minio-api.test.fedcloud.changeme via https://nsupdate.fedcloud.eu/
      type: string
    minio_letsencrypt_email:
      default: changeme@email.com
      description: Email to be used for Let's Encrypt certificates
      type: string

    # Restrict some simple-node-disk input values

    storage_size:
      type: scalar-unit.size
      description: Size of the extra HD added to the instance
      default: 50 GB
      constraints:
        - valid_values: [ 50 GB, 100 GB, 200 GB, 500 GB, 1 TB, 2 TB, 10 TB, 20 TB, 40 TB, 100 TB ]
    mount_path:
      type: string
      description: Path to mount the extra disk
      default: /data

  node_templates:

    minio:
      type: tosca.nodes.ec3.Application
      artifacts:
        docker_role:
          file: grycap.docker
          type: tosca.artifacts.AnsibleGalaxy.role
      capabilities:
        endpoint:
          properties:
            ports:
              port_http:
                protocol: tcp
                source: 80
              port_https:
                protocol: tcp
                source: 443
              port_api:
                protocol: tcp
                source: 9000
              port_console:
                protocol: tcp
                source: 9001
      interfaces:
        Standard:
          configure:
            implementation: https://raw.githubusercontent.com/grycap/tosca/main/artifacts/minio_compose.yml
            inputs:
              admin_pass:
                get_input: minio_secretkey
              admin_user:
                get_input: minio_accesskey
              dns_console:
                get_input: minio_dns_console
              dns_api:
                get_input: minio_dns_api
              letsencrypt_email:
                get_input: minio_letsencrypt_email
              release:
                get_input: minio_release
      requirements:
        - host: simple_node

    nsupdate_minio_api:
      type: tosca.nodes.ec3.Application
      interfaces:
        Standard:
          configure:
            implementation: https://raw.githubusercontent.com/grycap/tosca/main/artifacts/dydns_egi_update.yml
            inputs:
              dydns_hostname:
                get_input: minio_dns_api
              dydns_secret:
                get_input: nsupdate_secret_api
              new_ip:
                get_attribute: [ simple_node, public_address, 0 ]
      requirements:
        - host: simple_node

    nsupdate_minio_console:
      type: tosca.nodes.ec3.Application
      interfaces:
        Standard:
          configure:
            implementation: https://raw.githubusercontent.com/grycap/tosca/main/artifacts/dydns_egi_update.yml
            inputs:
              dydns_hostname:
                get_input: minio_dns_console
              dydns_secret:
                get_input: nsupdate_secret_console
              new_ip:
                get_attribute: [ simple_node, public_address, 0 ]
      requirements:
        - host: simple_node

  outputs:
    minio_console:
      value: { concat: [ 'https://', get_input: [ minio_dns_console ], '/' ] }
    minio_api:
      value: { concat: [ 'https://', get_input: [ minio_dns_api ], '/' ] }
