---
- hosts: localhost
  connection: local
  pre_tasks:
    - set_fact:
        minio_enable_ingress: false
        oscar_minio_endpoint: "https://{{ ansible_default_ipv4.address }}:30300"
        oscar_minio_tls_verify: false
      when: minio_dns_host == "" or minio_dns_host == "''"
    - set_fact:
        minio_enable_ingress: true
        oscar_minio_endpoint: 'https://{{ minio_dns_host }}'
        # oscar_minio_tls_verify: true
        oscar_minio_tls_verify: false
      when: minio_dns_host != "''" and minio_dns_host != ""
  roles:

    - role: 'grycap.kubeminio'
      minio_secretkey: '{{ oscar_minio_secretkey }}'
      master_deploy: true
      enable_tls: true
      enable_ingress: '{{ minio_enable_ingress }}'
      public_hostname_api: "{{ minio_dns_host }}"
      public_hostname_console: "{{ minio_dns_host_console }}"

    - role: 'grycap.kubefaas'
      faas_framework: 'knative'
      knative_version: '1.13.1'
      master_deploy: true

    - role: 'grycap.kubeoscar'
      oscar_pass: '{{ oscar_password }}'
      create_ingress: true
      minio_endpoint: '{{ oscar_minio_endpoint }}'
      minio_secret_key: '{{ oscar_minio_secretkey }}'
      master_deploy: true
      serverless_backend: "knative"
      minio_tls_verify: '{{ oscar_minio_tls_verify }}'
      additional_config:
        allowedImagePrefix: '{{ allowed_image_prefixes }}'
      oidc_issuer: "{{ oidc_issuers | default(['https://aai.egi.eu/auth/realms/egi']) | join(',') }}"
