---
- hosts: localhost
  connection: local
  vars:
    image: "{{ ai4eosc_model_image | default('plants-classification') }}"
    traefik_host: "{{ ansible_default_ipv4.address }}"
    cert_email: "{{ ai4eosc_cert_email | default('johndoe@server.com') }}"
  roles:
    - role: 'grycap.docker'
  tasks:
    - name: Create opt dir
      file:
        path: /opt/ai4eosc
        state: directory
        mode: '755'

    - name: Set traefik_host to Public IP
      set_fact:
        traefik_host: "{{ IM_NODE_PUBLIC_IP }}"
      when: IM_NODE_PUBLIC_IP is defined and IM_NODE_PUBLIC_IP != ""

    - name: Set traefik_host to DNS name
      set_fact:
        traefik_host: "{{ nsupdate_dns }}"
      when: nsupdate_dns is defined and nsupdate_dns != ""

    - name: Set "ai4oshub/" prefix to image if not set
      set_fact:
        image: "ai4oshub/{{ image }}"
      when: "'/' not in image"

    - name: Create docker-compose file
      copy:
        dest: /opt/ai4eosc/docker-compose.yaml
        mode: '644'
        content: |
          version: "3.9"
          services:
            app:
              image: {{ image }}
              labels:
                - "traefik.enable=true"
                - "traefik.http.routers.app.service=app"
                - "traefik.http.routers.app.rule=Host(`{{ traefik_host }}`)"
                - "traefik.http.routers.app.entrypoints=websecure"
                - "traefik.http.routers.app.tls.certresolver=myresolver"
                - "traefik.http.services.app.loadbalancer.server.port=5000"
            traefik:
                image: "traefik:v2.11"
                container_name: "traefik"
                command:
                  #- "--log.level=DEBUG"
                  - "--api.insecure=true"
                  - "--providers.docker=true"
                  - "--providers.docker.exposedbydefault=false"
                  - "--entrypoints.web.address=:80"
                  - "--entrypoints.websecure.address=:443"
                  - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
                  - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
                  - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
                  - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
                  - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
                  #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
                  - "--certificatesresolvers.myresolver.acme.email={{ cert_email }}"
                  - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
                ports:
                  - "80:80"
                  - "443:443"
                  - "8080:8080"
                volumes:
                  - "./letsencrypt:/letsencrypt"
                  - "/var/run/docker.sock:/var/run/docker.sock:ro"

    - name: Exec docker-compose up
      docker_compose:
        project_src: /opt/ai4eosc/
        state: present
