---
- hosts: localhost
  connection: local
  tasks:

    - name: Copy ansible tasks
      copy:
        content: "{{ ansible_tasks }}"
        dest: /tmp/{{ ansible_name }}_tasks.yaml
        mode: '644'
      when: ansible_tasks is defined and ansible_tasks != ""
      delegate_to: localhost

    - name: Download ansible tasks
      get_url:
        url: "{{ ansible_url }}"
        dest: /tmp/{{ ansible_name }}_tasks.yaml
        mode: '644'
      when: ansible_url is defined and ansible_url != ""
      delegate_to: localhost

    - name: Include tasks
      include_tasks:
        file: /tmp/{{ ansible_name }}_tasks.yaml
