---
- hosts: localhost
  connection: local
  tasks:
  - name: Install Apache and MySQL client packages on Debian-based systems
    apt:
      name:
        - apache2
        - mysql-client
    when: ansible_os_family == "Debian"
    
  - name: Install Apache and MySQL client packages on RedHat-based systems
    yum:
      name:
        - httpd
        - mysql
    when: ansible_os_family == "RedHat"
    
  - name: Install PHP and related packages
    package:
      name:
        - php
        - php-mysql
        - php-curl
        - php-xml