---
- hosts: localhost
  connection: local
  tasks:
  - name: Start Apache service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: Start Apache service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"