---
- hosts: localhost
  connection: local
  vars:
    docker_compose_folder: "{{ compose_folder | default('') }}"
    git_version: "{{ repo_branch | default('master') }}"
  roles:
    - role: 'grycap.docker'
  tasks:
    - name: Docker compose git
      when: docker_compose_git is defined and docker_compose_git != ""
      block:
        - name: Install git package
          package:
            name: git
            state: present
          ignore_errors: true

        - name: Clone docker-compose git repository
          git:
            repo: '{{ docker_compose_git }}'
            dest: /opt/docker_compose
            version: "{{ git_version }}"

        - name: docker-compose up
          community.docker.docker_compose_v2:
            project_src: "/opt/docker_compose/{{ docker_compose_folder }}"
            state: present
