---
- name: Install datahugger and download dataset
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure python3-pip is installed
      ansible.builtin.package:
        name: python3-pip
        state: present

    - when: remote_storage_endpoint is not defined or remote_storage_endpoint == ""
      block:

        - name: Set extra_args var
          set_fact:
            extra_args: ""

        - name: Set extra_args var in py3.11
          set_fact:
            extra_args: --break-system-packages
          when: ansible_python_version is version('3.11', '>=')

        - name: Install datahugger Python module
          ansible.builtin.pip:
            # name: datahugger
            name: "git+https://github.com/grycap/datahugger/"
            state: present
            executable: pip3
            extra_args: "{{ extra_args }}"

        - name: Download the dataset
          grycap.dataset.download_dataset:
            dataset_url: "{{ dataset_url }}"
            output_dir: "{{ output_dir }}"
            owner: "{{ owner | default('') }}"

    - when: remote_storage_endpoint is defined and remote_storage_endpoint != ""
      block:
        - name: FTS Dataset
          debug:
            msg: FTS Dataset
