---
- name: Install datahugger and download dataset
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure python3-pip is installed
      ansible.builtin.package:
        name: python3-pip
        state: present

    - when: remote_storage_endpoint is not defined or remote_storage_endpoint == ""
      block:

        - name: Install datahugger Python module
          ansible.builtin.pip:
            name: datahugger
            state: present
            executable: pip3

        - name: Download the dataset
          grycap.dataset.download_dataset:
            dataset_url: "{{ dataset_url }}"
            output_dir: "{{ output_dir }}"

    - when: remote_storage_endpoint is defined and remote_storage_endpoint != ""
      block:
        - name: mount remote storage
          command: echo "mounting remote storage"
