---
- hosts: localhost
  tasks:
    - name: Submit DTS transfer
      grycap.dataset.transfer_dataset_dts:
        dataset_doi: "{{ dataset_url }}"
        dts_endpoint: https://data-transfer.service.eosc-beyond.eu
        dts_token: "{{ dts_credential['token'] }}"
        destination: "{{ remote_storage_endpoint }}{{ remote_storage_path }}"
        destination_type: "{{ remote_storage_type }}"
        dest_authorization: "{{ remote_storage_credentials | default({}) }}"
        overwrite: "{{ remote_storage_overwrite | default(false) }}"
      register: dts_job

    - name: Print JobID
      debug:
        var: dts_job
