---
- hosts: localhost
  connection: local
  vars:
    vnode_prefix: vnode-
  pre_tasks:
    - set_fact:
        KUBERNETES_TOKEN: "{{ clues_kube_token }}"
      when: clues_kube_token != ""
  roles:
    - role: grycap.im
    - role: grycap.clues
  tasks:
    - name: Set IM plugin IM_VIRTUAL_CLUSTER_TOSCA to True
      ini_file: dest=/etc/clues2/conf.d/plugin-im.cfg section="IM VIRTUAL CLUSTER" option=IM_VIRTUAL_CLUSTER_TOSCA value="True" mode='644'
      notify: restart cluesd
    - name: Download is_cluster_ready
      get_url:
        url: https://raw.githubusercontent.com/grycap/tosca/refs/tags/v1.0.0/artifacts/is_cluster_ready
        dest: /bin/is_cluster_ready
        mode: '755'
