---
- hosts: localhost
  tasks:
    - name: Submit FTS transfer
      grycap.dataset.transfer_dataset_dts:
        dataset_doi: "{{ dataset_url }}"
        dts_endpoint: https://data-transfer.service.eosc-beyond.eu
        dts_token: "{{ fts_credential['token'] }}"
        destination: "{{ remote_storage_endpoint }}{{ remote_storage_path }}"
