---
- hosts: localhost
  vars:
    fts_endpoint: https://data-transfer.service.eosc-beyond.eu/
  tasks:
    # TODO: All the values and format are tentative and need to be replaced
    # See: https://github.com/EGI-Federation/eosc-data-transfer
    # https://fts3-docs.web.cern.ch/fts3-docs/fts-rest/docs/api.html
    - name: Submit FTS transfer
      ansible.builtin.uri:
        url: "{{ fts_endpoint }}/transfers"
        method: POST
        status_code: 202
        headers:
          Accept: application/json
          Content-Type: application/json
          Authorization: "Bearer {{ fts_credential['token'] }}"
        body_format: json
        body: |
          {
              "files": [
                {
                  "sources": ["{{ dataset_url }}"],
                  "destinations": ["{{ remote_storage_endpoint }}{{ remote_storage_path }}"]
                }
              ],
              "params": {
                "verifyChecksum": true,
                "overwrite": true,
                "retry": 0
              }
          }
