---
- hosts: localhost
  connection: local
  vars:
    # defalt pass is "operatorpass"
    GOACCESS_PASSWORD: "{{ mlflow_operator_pass | default('$$2y$$05$$lPcMyqoHliTPF5QeAHoPWOGyLFZxGQg.pSfJlHssQJ9Ny7OFcSI3i') }}"
    MLFLOW_USERNAME: "{{ mlflow_admin_user | default('admin') }}"
    MLFLOW_PASSWORD: "{{ mlflow_admin_password | default('password') }}"
    OIDC_AUTHORITY: "{{ mlflow_oidc_auth | default('https://aai-demo.egi.eu/auth/realms/egi') }}"
    OIDC_CLIENT_ID: "{{ mlflow_oidc_client_id | default('oidc-client') }}"
    OAUTH_USERINFO_ENDPOINT: "{{ mlflow_auth_userinfo_endpoint | default(OIDC_AUTHORITY + '/protocol/openid-connect/userinfo') }}"
    SUPPORTED_VO: "{{ mlflow_oidc_vo | default('vo.ai4eosc.eu') }}"
    REQUIRED_ENTITLEMENT: "{{ mlflow_required_entitlement | default('urn:mace:egi.eu:group:' + SUPPORTED_VO + ':role=member#aai.egi.eu') }}"
  roles:
    - role: 'grycap.docker'
  tasks:
    - name: Clone git repository
      git:
        repo: https://github.com/m-team-kit/mlflow-auth-gui
        dest: /opt/mlflow-auth-gui/mlflow-auth-gui/
        version: main
      ignore_errors: true

    - name: Set default DNS name (nip.io)
      set_fact:
        dns_name: "mlflow.{{ public_ip_address }}.nip.io"
      when: mlflow_dns_name is not defined or mlflow_dns_name == ""
    - name: Set custom DNS name
      set_fact:
        dns_name: "{{ mlflow_dns_name }}"
      when: mlflow_dns_name is defined and mlflow_dns_name != ""

    - name: Set admin username and password in ini file
      ini_file:
        path: /opt/mlflow-auth-gui/mlflow-auth-gui/backend/srv/auth_config.ini
        section: "mlflow"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        mode: '0644'
      loop:
        - { "option": "admin_username", "value": "{{ MLFLOW_USERNAME }}" }
        - { "option": "admin_password", "value": "{{ MLFLOW_PASSWORD }}" }

    - name: Create .env file
      copy:
        dest: /opt/mlflow-auth-gui/mlflow-auth-gui/.env
        mode: '0644'
        content: |
          # Domain where MLFLOW is hosted
          DOMAIN={{ dns_name }}
          # POSTGRES CONFIG
          DATABASE_NAME=mlflowdb
          DATABASE_USER=postgres
          DATABASE_PASSWORD=dummypassword
          DATABASE_HOST=database
          DATABASE_PORT=5432
          # MLFLOW Authentication Database File
          AUTH_DB_FILE=basic_auth.db
          # Local (host) BASE PATH to store MLFLOW data, e.g. app-data, user-data, artifacts, backup_db.
          # Pay attention about subdirectories ownership, may need to set uid:gid of "docker"
          MLFLOW_BASE_PATH_LOCAL=/opt/mlflow-auth-gui/mlflow-auth-gui/
          # MLflow user registration service
          MLFLOW_USERNAME={{ MLFLOW_USERNAME }}
          MLFLOW_PASSWORD={{ MLFLOW_PASSWORD }}
          MLFLOW_HOSTNAME=http://backend:5000
          OIDC_AUTHORITY={{ OIDC_AUTHORITY }}
          OIDC_CLIENT_ID={{ OIDC_CLIENT_ID }}
          OAUTH_USERINFO_ENDPOINT={{ OAUTH_USERINFO_ENDPOINT }}
          REQUIRED_ENTITLEMENT={{ REQUIRED_ENTITLEMENT }}
          PRIVACY_POLICY_URL=https://confluence.egi.eu/display/IMPAIP/Privacy+Policy
          TERMS_OF_USE_URL=https://confluence.egi.eu/display/IMPAIP/Acceptable+Use+Policy
          # can be left blank, but prefer putting one
          LETSENCRYPT_EMAIL={{ mlflow_cert_email }}
          CORS_ORIGINS=http://localhost,http://foo.bar
          # Monitoring based on goaccess
          GOACCESS_ETC_PATH_LOCAL=${MLFLOW_BASE_PATH_LOCAL}/goaccess-etc
          GOACCESS_OUT_PATH_LOCAL=${MLFLOW_BASE_PATH_LOCAL}/goaccess-out
          GOACCESS_WEB_ROUTE=goaccess
          GOACCESS_USER=operator
          GOACCESS_PASSWORD={{ GOACCESS_PASSWORD }}     # bcrypt encrypted password, use "htpasswd -B -n operator" to generate. use $$ instead of $ in GOACCESS_PASSWORD value
          GOACCESS_ACCESSLOG_FORMAT=TRAEFIKCLF

    - name: Exec docker-compose up
      community.docker.docker_compose_v2:
        project_src: /opt/mlflow-auth-gui/mlflow-auth-gui/
        state: present
        files:
          - compose.yml
          - compose.prod.yml
