---
- hosts: localhost
  connection: local
  tasks:
  - name: Install MySQL Python dependencies
    package:
      name: python3-pymysql
      state: present

  - name: Set MySQL root password and authentication method
    mysql_user:
      name: root
      host: localhost
      password: "{{ mysql_root_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present

  - name: Create MySQL database
    community.mysql.mysql_db:
      name: "{{ db_name }}"
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"

  - name: Create MySQL user
    community.mysql.mysql_user:
      name: "{{ db_user }}"
      password: "{{ db_password }}"
      host: "{{ db_access_host }}"
      priv: "{{ db_name }}.*:ALL"
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"
