---
- hosts: localhost
  connection: local
  tasks:
  - name: MySQL | Make sure the MySQL packages are installed
    package:
      name: mysql-server

  - name: Ensure MySQL service is started and enabled
    service:
      name: mysql
      state: started
      enabled: yes
