---
- hosts: localhost
  connection: local
  tasks:
  - name: Download and extract WordPress
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/html/
      remote_src: yes
    args:
      creates: /var/www/html/wordpresswp-config-sample.php
